version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting image tag from source version
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo AWS region is $AWS_DEFAULT_REGION
      - REGISTRY=$(echo $APP_IMAGE | cut -d'/' -f1)
      - echo Logging into ECR registry $REGISTRY
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY
      - echo Image URI base $APP_IMAGE
      - echo Image Tag $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image
      - docker build -t $APP_IMAGE:$IMAGE_TAG -t $APP_IMAGE:latest .

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push $APP_IMAGE:$IMAGE_TAG
      - docker push $APP_IMAGE:latest
      - echo $APP_IMAGE:$IMAGE_TAG > image_uri.txt

artifacts:
  files:
    - image_uri.txt
