version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI v2...
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - ./aws/install -i /usr/local/aws -b /usr/local/bin
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $APP_IMAGE
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $APP_IMAGE:latest .
      - docker tag $APP_IMAGE:latest $APP_IMAGE:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $APP_IMAGE:latest
      - docker push $APP_IMAGE:$CODEBUILD_RESOLVED_SOURCE_VERSION

